### ISSUE TITLE
About JDK version

### ISSUE THREAD

**Issue by EKwongChum** [RxGirlz/OpenYspider#2]
你好，关于Java版本有一些建议。
克隆了项目下来，跑了一下，发现是用的Java 11，打开项目细看，只有在
 MeinvlaTypeEnum.java 里用到了Java 11 的语法

```java
    public static List<MeinvlaTypeEnum> getEnums() {
        return List.of(values());
    }
```

当前用Java 8的开发者应该比较多，是否可以改一下呢？
这样或许更多的开发者参与到这个项目中。

**Comment by gdut-yy** [comment]
感谢你的建议，考虑到当前 Java 11 的普及性，已采纳你的 pr
