### ISSUE TITLE
java.sql.SQLSyntaxErrorException: Table 'hhhhh.tbl_tujidao_album' doesn't exist

### ISSUE THREAD

**Issue by incubus-ohy** [RxGirlz/OpenYspider#5]
java.sql.SQLSyntaxErrorException: Table 'hhhhh.tbl_tujidao_album' doesn't exist

**Comment by gdut-yy** [comment]
短期方案：代码里面的 mybatis-plus 表名和全量脚本的表名对应不上，修改任意一处使二者相等即可

/*==============================================================*/
/* Table: OYS_TUJIDAO_ALBUM                                     */
/*==============================================================*/
CREATE TABLE TBL_TUJIDAO_ALBUM
(
   ID                   NUMERIC(22,0) NOT NULL  COMMENT '主键 ID',
   STATE                NUMERIC(3,0)  COMMENT '状态',
   TOTAL                NUMERIC(11,0)  COMMENT '图片总数',
   ALBUM_NAME           VARCHAR(255)  COMMENT '相册名',
   ALBUM_ID             NUMERIC(22,0)  COMMENT '相册id',
   TYPE                 NUMERIC(3,0)  COMMENT '相册类型',
   CREATION_DATE        DATETIME DEFAULT CURRENT_TIMESTAMP  COMMENT '创建时间',
   LAST_UPDATED_BY      DATETIME DEFAULT CURRENT_TIMESTAMP  COMMENT '最后修改时间',
   PRIMARY KEY (ID),
   KEY ALBUM_ID_UNIQUE (ALBUM_ID)
);

**Comment by gdut-yy** [comment]
@incubus-ohy 长期方案，提供 pr 进行 fix

**Comment by RxGirlz** [comment]
fixed by 30e45b9350c4ac2dbeb261d0d87e8b23b0e5a0e2
